### ISSUE TITLE
Delay in showing actual filestructure

### ISSUE THREAD

**Issue by rudibroekhuizen** [cyverse/irodsfs#16]
Hi, I'm using irodsfs in a docker container. This al works fine but when I create a file or a folder in irods, it only shows up in my mounted irodsfs volume minutes later. 

This is the dockerfile I use to build a container:
`https://gitlab.com/arise-biodiversity/biocloud/docker-compose-biocloud-lrp/-/blob/dev/nginx/Dockerfile`

Commands to start irodfs:
```
docker compose exec nginx bash
irodsfs -allow_other irods://rods:irods@irods/tempZone /mnt/irodsfs/tempZone
```
```
{
  "clientVersion": "v0.7.1",
  "gitCommit": "a6ced0565756f46558828174be207f2ae6180c45",
  "buildDate": "2022-06-23T08:30:07Z",
  "goVersion": "go1.18.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by iychoi** [comment]
Hi, 
If I understand your question correctly, you created a new file or a directory in iRODS using icommands or any other iRODS clients. Then you wanted to see it in irodsfs mounted directory. Is this correct?

This is intended because irodsfs does not know when iRODS filesystem is changed. The only way is checking iRODS filesystem periodically (currently 5min default). However, checking iRODS filesystem too frequently creates too many iRODS API requests and responses, so slows down performance. For the reason, irodsfs, by default, caches filesystem metadata for 5 minutes. So, in the worst case, you will see a new file or a directory 5 minutes after you create it via icommands or other programs.

There's a command line argument `--metadata_cache_timeout` to control the cache timeout. You can set a very small number, such as `1s` as the value.
